---
extension:
  api:
    twitter:
      oauth:
        base-url: https://api.twitter.com/oauth2/token
        connect-timeout: 10000
        read-timeout: 10000
        max-in-memory-size: 16777216
        api-key: ${API_KEY}
        api-secret: ${API_SECRET}
      favorite:
        base-url: https://api.twitter.com/1.1/favorites/create.json
        connect-timeout: 10000
        read-timeout: 10000
        max-in-memory-size: 16777216
        api-key: ${API_KEY}
        api-secret: ${API_SECRET}
    google:
      auth:
        base-url: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/identity?audience=FUNCTION_URL
        connect-timeout: 10000
        read-timeout: 10000
        max-in-memory-size: 16777216
      udb:
        base-url: https://us-central1-ii-ne-bot-staging.cloudfunctions.net/api/v1/oauth/favorite/
        connect-timeout: 10000
        read-timeout: 10000
        max-in-memory-size: 16777216
